name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Apiformes
      run: (cd apiformes && cargo build --verbose)
    - name: Test Apiformes
      run: (cd apiformes && cargo test --verbose --all-features)
    - name: Build Server
      run: (cd apiformes-server && cargo build --verbose release)
    - name: Build BM
      run: (cd apiformes-bm && cargo build --verbose --release)
